# This file is locked for GovCMS SaaS.
include:

  # Simple control of your jobs.
  - local: '/.gitlab-ci-inputs.yml'

  # The primary default GovCMS GitLab CI configuration.
  - project: 'govcms/scaffold-tooling'
    ref: "0.1.2"
    file: '.gitlab-ci-main.yml'
