image: govcmsdev/gitlab-ci
services:
- docker:dind
stages:
- build
- deploy
build:
  stage: build
  script:
    - "export DOCKER_HOST=tcp://localhost:2375"
    - "docker network prune -f && docker network create amazeeio-network"
    - "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab-registry-production.govcms.amazee.io"
    - "docker-compose up -d"
    - "docker-compose exec -T test dockerize -wait tcp://mariadb:3306 -timeout 1m"
    - |
      docker-compose exec -T cli composer install
      if ! grep --quiet '^MARIADB_DATA_IMAGE' .env; then
        echo "MARIADB_DATA_IMAGE is not set. @see https://govcms.gov.au/wiki_vars#MARIADB_DATA_IMAGE"
        docker-compose exec -T cli drush si -y govcms
      fi
      docker-compose exec -T cli govcms-deploy
    - ahoy lint || true
deploy:
  stage: deploy
  script:
    - "echo \"curl -X POST -d projectName=$CI_PROJECT_NAME -d branchName=$CI_COMMIT_REF_NAME http://rest2tasks.lagoon.svc:3000/deploy\""
    - "curl -X POST -d projectName=$CI_PROJECT_NAME -d branchName=$CI_COMMIT_REF_NAME http://rest2tasks.lagoon.svc:3000/deploy"
