docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: Deploy GovCMS
        command: govcms-deploy
        service: cli

environments:
  master:
    types:
      mariadb: mariadb-shared
    cronjobs:
      - name: drush cron
        schedule: "0 * * * *"
        command: 'drush cron --root=/app'
        service: cli
