##
# File /etc/drush/sites/ci.site.yml
# @todo move upstream, see Dockerfile.cli
#
# This is used in integration and workflow processes in Openshift and GitLab.
# It is not intended to be used by clients.
# Run with `drush --alias-path=/etc/drush/sites ci.ALIASNAME`
#

prod:
  root: /app
  host: ssh.lagoon.svc
  user: ${env.LAGOON_PROJECT}-master
  uri: nginx-${env.LAGOON_PROJECT}-master.govcms.amazee.io
  ssh:
    options: -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2020 -F /dev/null
